# Indicamos la versión
version: '3.7'

# Mis servicios
# Iniciamos los servicios
services:

  # API REST TS
  ts-api-rest:
    container_name: ts-api-rest
    # image: "joseluisgs/ts-api-rest"
    build: .
    ports:
      - 8000:8000
    volumes:
      - api-files:/app/build/public
    networks:
      - api-network
    depends_on:
      - mariadb-server
    # restart: always
  
  # MARIA DB
  mariadb-server:
    image: mariadb
    # restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mariapass
      MYSQL_USER: mariaadmin
      MYSQL_PASSWORD: mariapass
      MYSQL_DATABASE: ts-api-rest
    volumes:
      - api-maria:/var/lib/mysql
    networks:
      - api-network
    # restart: always

  # MONGO EXPRESS
  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080
    networks:
      - api-network
    depends_on:
      - mariadb-server

# Mi volumenes de datos compartidos
volumes:
  api-files:
  api-maria:

# Si queremos que tengan una red propia a otros contenedores
networks:
  api-network:
    driver: bridge
